config_iot:
  mqtt:
    server_url: "broker.mqttdashboard.com"        # http://www.hivemq.com/demos/websocket-client/
    server_port: 1883
    topic_sub: "eyrc/mMoOnNuU/iot_to_ros"          # <unique_id> = xYzqLm
    topic_pub: "eyrc/mMoOnNuU/ros_to_iot"          # <unique_id> = xYzqLm
    qos: 0

    sub_cb_ros_topic: "/ros_iot_bridge/mqtt/sub"   # ROS nodes can listen to this topic to receive data from MQTT
  google_apps:
    spread_sheet_id: "AKfycbwj5fMei0u8zMUoh4xmsp2nteKkQOBmKznQrZGJhKB6mzWfyqs"